name: gestion_etudiants
description: "Mini application de gestion des étudiants (architecture MVVM)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Gestion d'état pour l'architecture MVVM (le ViewModel = ChangeNotifier)
  provider: ^6.1.5+1
  # Persistance locale des données (les étudiants survivent à la fermeture)
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
